const base = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000";
async function request<T>(path: string, init?: RequestInit): Promise<T> { const r = await fetch(`${base}/api${path}`, init); if (!r.ok) throw new Error(`Request failed (${r.status})`); return r.json() as Promise<T>; }
export type Brand = { id: string; name: string };
export type Threat = { id:string; name:string; source:string; publisher?:string|null; threat_type:string|null; risk_score:number; severity:string; status:string; detected_at:string };
export type Overview = { brand:Brand; summary:Record<string,number>; risk_distribution:{severity:string;count:number}[]; source_distribution:{source:string;count:number}[]; threat_type_distribution:{threat_type:string;count:number}[]; recent_threats:Threat[]; last_scan:{completed_at:string|null;candidate_count:number}|null };
export type Detection = { id:string; risk_score:number; severity:string; threat_type:string|null; status:string; detected_at:string; candidate:{name:string;source:string;publisher?:string|null}; evidence:{signal_type:string;available:boolean;score:number|null;details:Record<string,unknown>}[] };
export type Note={id:string;content:string;actor:string;created_at:string}; export type Activity={id:string;event_type:string;previous_value:string|null;new_value:string|null;details:Record<string,unknown>;actor:string;created_at:string}; export type Draft={id:string;draft_type:string;content:string;evidence_summary:string[];created_at:string}; export type Investigation={detection_id:string;status:string;notes:Note[];activity:Activity[];drafts:Draft[]};
const post=<T>(path:string,body:unknown)=>request<T>(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
export const api = { brands:()=>request<Brand[]>("/brands"), overview:(id:string)=>request<Overview>(`/dashboard/overview?brand_id=${id}`), scan:(id:string)=>post("/monitoring/scan",{brand_id:id}), detections:()=>request<Detection[]>("/detections"), detection:(id:string)=>request<Detection>(`/detections/${id}`), investigation:(id:string)=>request<Investigation>(`/detections/${id}/investigation`), status:(id:string,status:string)=>post<Investigation>(`/detections/${id}/status`,{status}), note:(id:string,content:string)=>post<Investigation>(`/detections/${id}/notes`,{content}), draft:(id:string,draft_type:string)=>post<Draft>(`/detections/${id}/remediation-drafts`,{draft_type}) };
